name: Deploy to DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 (DEV)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu || exit 1

            if [ ! -d node-multi-env-devops ]; then
              git clone https://github.com/pavananingi/node-multi-env-devops.git
            fi

            cd node-multi-env-devops/app

            docker stop myapp-dev || true
            docker rm myapp-dev || true

            docker build -t myapp:dev .

            docker run -d \
              --name myapp-dev \
              --env-file /home/ubuntu/.env.dev \
              -p 3001:3000 \
              myapp:dev
