name: Deploy to PROD

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 (PROD)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu || exit 1

            if [ ! -d node-multi-env-devops ]; then
              git clone https://github.com/pavananingi/node-multi-env-devops.git
            fi

            cd node-multi-env-devops/app

            docker stop myapp-prod || true
            docker rm myapp-prod || true

            docker build -t myapp:prod .

            docker run -d \
              --name myapp-prod \
              --env-file /home/ubuntu/.env.prod \
              -p 3000:3000 \
              myapp:prod
